# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMC5ZpOS88cts5fCKmlJLui4xzgDM_Fy
"""

print("Hello World!")

import mysql.connector
from mysql.connector import Error

hostname = "qisitj.h.filess.io"
database = "olistproject_sweetgetof"
port = "3307"
username = "olistproject_sweetgetof"
password = "7a0bfd049e69c7104c5893aea716f460d2b496e5"

try:
    connection = mysql.connector.connect(host=hostname, database=database, user=username, password=password, port=port)
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor = connection.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)

except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

pip install mysql-connector-python

import pandas as pd

order_payments = pd.read_csv("olist_order_payments_dataset.csv")
order_payments.head()

import pandas as pd
import mysql.connector
from mysql.connector import Error

#connection details
hostname = "qisitj.h.filess.io"
database = "olistproject_sweetgetof"
port = "3307"
username = "olistproject_sweetgetof"
password = "7a0bfd049e69c7104c5893aea716f460d2b496e5"

csv_file_path = "olist_order_payments_dataset.csv"

table_name = "olist_order_payments"

try:
    connection = mysql.connector.connect(host=hostname, database=database, user=username, password=password, port=port)
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)

        cursor = connection.cursor()

        cursor.execute(f"DROP TABLE IF EXISTS {table_name};")
        print(f"Table '{table_name}'dropped if it existed.")

        create_table_query = f"""
        CREATE TABLE {table_name} (
          order_id VARCHAR(50),
          payment_sequential INT,
          payment_type VARCHAR(20),
          payment_installments INT,
          payment_value FLOAT
        );
        """

        cursor.execute(create_table_query)
        print(f"Table {table_name} is created successfully!")

        data = pd.read_csv(csv_file_path)
        print(f"CSV data loaded into pandas Dataframe.")

        batch_size = 1000
        total_records = len(data)

        print(f"start data insertion into '{table_name}' in batches of {batch_size} records.")
        for start in range(0, total_records, batch_size):
          end = start + batch_size
          batch = data.iloc[start:end]

          batch_records = [
              tuple(row) for row in batch.itertuples(index = False, name=None)
          ]

          insert_query = f"""
          INSERT INTO {table_name}
          (order_id, payment_sequential, payment_type, payment_installments, payment_value)
          VALUES (%s, %s, %s, %s, %s); """

          cursor.executemany(insert_query, batch_records)
          connection.commit()
          print(f"inserted records {start + 1} to {min(end, total_records)} successfully.")

        print(f"All {total_records} records inserted successfully into `{table_name}`.")

except Error as e:
    print("Error while connecting to MySQL or inserting data:", e)
finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

pip install pymongo

# importing module
from pymongo import MongoClient

hostname = "5-x8xl.h.filess.io"
database = "olistDataNoSQL_friendgot"
port = "61004"
username = "olistDataNoSQL_friendgot"
password = "599427d546d0c4e7a57bb4a06f113faf0214efc7"

uri = "mongodb://" + username + ":" + password + "@" + hostname + ":" + port + "/" + database

# Connect with the portnumber and host
client = MongoClient(uri)

# Access database
mydatabase = client[database]

pip install pymongo

import pandas as pd
from pymongo import MongoClient

# Load the CSV file into a pandas DataFrame
csv_file_path = "product_category_name_translation.csv"
data = pd.read_csv(csv_file_path)

hostname = "5-x8xl.h.filess.io"
database = "olistDataNoSQL_friendgot"
port = "61004"
username = "olistDataNoSQL_friendgot"
password = "599427d546d0c4e7a57bb4a06f113faf0214efc7"

uri = "mongodb://" + username + ":" + password + "@" + hostname + ":" + port + "/" + database

# Connect with the portnumber and host
client = MongoClient(uri)

# Access database
mydatabase = client[database]

# Access the desired collection (creates it if it doesn't exist)
collection_name = "product_category_translation"
mycollection = mydatabase[collection_name]

# Convert DataFrame to a list of dictionaries (one dictionary per row)
data_dict = data.to_dict(orient='records')

# Insert the data into the MongoDB collection
try:
    mycollection.insert_many(data_dict)
    print(f"Successfully inserted {len(data_dict)} records into the '{collection_name}' collection.")
except Exception as e:
    print(f"Error inserting data into MongoDB: {e}")
finally:
    if 'client' in locals() and client:
        client.close()
        print("MongoDB connection is closed.")